inventory.insert=INSERT INTO inventory (product_id, available_qty) VALUES (?, ?)
inventory.findById=SELECT product_id, available_qty FROM inventory WHERE product_id=?

inventory.deduct=UPDATE inventory SET available_qty = available_qty - ? WHERE product_id = ? AND available_qty >= ?

inventory.restore=UPDATE inventory SET available_qty = available_qty + ? WHERE product_id = ?